'use client'

import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'
import type { QueryGroup as QueryGroupType, Schema } from '@/types/query'
import { generateSQL, generateMongo, generateGraphQL } from '@/utils'

const PDF_COLORS = {
  text: '#111111',
  textMuted: '#666666',
  textFaint: '#888888',
  border: '#e2e2dd',
  codeBg: '#0d0d0d',
  codeText: '#e0e0e0',
  footer: '#aaaaaa',
} as const

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
    backgroundColor: '#ffffff',
    color: PDF_COLORS.text,
  },
  header: {
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: PDF_COLORS.border,
    borderBottomStyle: 'solid',
  },
  brand: {
    fontSize: 18,
    fontFamily: 'Helvetica-Bold',
    color: PDF_COLORS.text,
  },
  meta: {
    fontSize: 9,
    color: PDF_COLORS.textMuted,
    marginTop: 4,
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: PDF_COLORS.textFaint,
    marginBottom: 6,
  },
  codeBlock: {
    backgroundColor: PDF_COLORS.codeBg,
    borderRadius: 4,
    padding: 12,
  },
  code: {
    fontFamily: 'Courier',
    fontSize: 8,
    color: PDF_COLORS.codeText,
    lineHeight: 1.6,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 8,
    color: PDF_COLORS.footer,
    textAlign: 'center',
    borderTopWidth: 0.5,
    borderTopColor: PDF_COLORS.border,
    borderTopStyle: 'solid',
    paddingTop: 10,
  },
})

function CodeBlock({ text }: { text: string }) {
  return (
    <View style={styles.codeBlock}>
      {text.split('\n').map((line, i) => (
        <Text key={i} style={styles.code}>{line || ' '}</Text>
      ))}
    </View>
  )
}

interface QueryPDFProps {
  tree: { root: QueryGroupType }
  schema: Schema
  exportedAt: string
}

export function QueryPDF({ tree, schema, exportedAt }: QueryPDFProps) {
  const sql = generateSQL(tree.root, schema.name.toLowerCase())
  const mongo = generateMongo(tree.root)
  const graphql = generateGraphQL(tree.root, schema.name.toLowerCase(), schema.fields.map(f => f.name))

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>FILTRO</Text>
          <Text style={styles.meta}>
            Schema: {schema.name}  •  Exported: {exportedAt}
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>SQL</Text>
          <CodeBlock text={sql} />
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>MONGODB</Text>
          <CodeBlock text={mongo} />
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>GRAPHQL</Text>
          <CodeBlock text={graphql} />
        </View>

        <Text style={styles.footer} fixed>Generated by Filtro  •  Visual Query Builder</Text>
      </Page>
    </Document>
  )
}
